### ISSUE TITLE
Add a Flutter Project using Provider

### ISSUE THREAD

**Issue by saty-a** [saty-a/FlutterHub#11]
We're looking to expand our collection of Flutter projects in FlutterHub with a new project that demonstrates the power of the Provider package for state management. If you have experience with Provider and would like to contribute, this is your chance to showcase your skills!

**Comment by Sandesh-03** [comment]
can I add a project?

**Comment by saty-a** [comment]
Sure @Sandesh-03

**Comment by saty-a** [comment]
Please give a star if like this repo!! @Sandesh-03

**Comment by Sandesh-03** [comment]
Sure
