### ISSUE TITLE
Create CONTIBUTION.md

### ISSUE THREAD

**Issue by Ronit-gurjar** [saty-a/FlutterHub#14]
hey @saty-a 🔥

your idea for FlutterHub seems great💡
I think you should have a Contribution guidelines file to explains the rules of contribution and also unclutter the README.md file

if you think the idea is great, pls assign this issue to me under `hactoberfest` label

**Comment by saty-a** [comment]
Sure 

> hey @saty-a 🔥
> 
> your idea for FlutterHub seems great💡 I think you should have a Contribution guidelines file to explains the rules of contribution and also unclutter the README.md file
> 
> if you think the idea is great, pls assign this issue to me under `hactoberfest` label

Sure thing @Ronit-gurjar

**Comment by saty-a** [comment]
Hey @Ronit-gurjar by the way there is telegram contest going on for creating Icons for Android and IOS both I've just seen, You may join that great contest!!

**Comment by Ronit-gurjar** [comment]
> Owner

oh sorry but i won't be able to participate in that, but thanks for letting me know🔥
